version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10.1
    resource_class: small
    steps:
      - checkout
      - run: 
          name: Upgrade pip
          command: /home/circleci/.pyenv/versions/3.10.1/bin/python3.10 -m pip install --upgrade pip
      - run: 
          name: Insall Dependices
          command: pip3 install requests
      - run: 
          name: Extend
          command: python3 run.py -u $USERNAME -p $PASSWORD

parameters:
  run-schedule:
    type: boolean
    default: false

workflows:
  commit:
    jobs:
      - build
  extend:
    when: << pipeline.parameters.run-schedule >>
    jobs:
      - build
